general_settings:
  database_url: os.environ/DATABASE_URL
  master_key: os.environ/LITELLM_MASTER_KEY
litellm_settings:
  drop_params: true
  json_logs: true
  request_timeout: 300
  store_prompts_in_spend_logs: true
model_list:
- litellm_params:
    allowed_openai_params:
    - max_tokens
    - max_completion_tokens
    - reasoning_effort
    - temperature
    - top_p
    - stream
    - stop
    - tools
    - tool_choice
    - frequency_penalty
    - presence_penalty
    - n
    - user
    - response_format
    - seed
    api_base: os.environ/NV_BASEURL
    api_key: os.environ/NV_KEY4
    model: openai/z-ai/glm-5.1
    rpm: 100
    timeout: 300
  model_info:
    max_tokens: 131072
    mode: chat
  model_name: nvglm5.1k4
- litellm_params:
    allowed_openai_params:
    - max_tokens
    - max_completion_tokens
    - temperature
    - top_p
    - stream
    - stop
    - tools
    - tool_choice
    - frequency_penalty
    - presence_penalty
    - n
    - user
    - response_format
    - seed
    api_base: os.environ/NV_BASEURL
    api_key: os.environ/NV_KEY4
    model: openai/deepseek-ai/deepseek-v4-pro
    rpm: 100
    timeout: 300
  model_info:
    max_tokens: 131072
    mode: chat
  model_name: nvdsv4pk4
router_settings:
  allowed_fails: 0
  bitmask_allowed_fails: 0
  bitmask_allowed_fails_gc_time: 0
  cooldown_time: 0
  enable_pre_call_checks: false
  model_group_alias: null
  num_retries: 0
  routing_strategy: simple-shuffle
